language: python
python:
  - "3.6"

install:
  - pip install pytest-cov
  - pip install coveralls

script:
  - pytest --cov-report term-missing --cov=translate

after_success:
  - coveralls

notifications:
  email: false