language: python
cache: pip
python:
  - "3.6"

script:
  - pytest --cov-report term-missing --cov=translate

after_script:
  - pip install --quiet coveralls
  - coverage run setup.py test
  - coveralls

notifications:
  email: false
